runtime: python39
entrypoint: gunicorn -b :$PORT app:app

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

env_variables:
  DB_HOST: 'cloudkwic:us-central1:micro-miner-db-instance'
  DB_USER: 'root'
  DB_PASSWORD: '123456'
  DB_NAME: 'microminerDatabase'

# Ensure Cloud SQL Proxy is started as a service
#services:
#- name: cloudsqlproxy
#  url: /cloudsql
#  script: start_cloudsql_proxy.sh